### ISSUE TITLE
[QUESTION] filename '\'

### ISSUE THREAD

**Issue by vashian** [isaacs/node-tar#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi
I have a file with the name: `\`

![image](https://user-images.githubusercontent.com/92857147/216946191-62486cfd-fe48-4499-a0da-308587a4b97a.png)

Using the command `tar -czvf <filename>  <location>` everything is ok and I can extract it without any problem but when I use the **node-tar** package and create `.tar.gz` file I couldn't extract it.

Node-tar version: 6.1.13

### Environment

- npm: 8.19.2
- Node: v18.12.0
- OS: Ubuntu 22.04.1 LTS x86_64

**Comment by isaacs** [comment]
That's a tricky one, because an explicit goal of this implementation is to work as identically as possible across win32 and posix platforms.

On windows, `\` is not a valid filename, it's a path separator.  So I don't really see a way to support this in node-tar, without abandoning that portability.

Can I ask what you use that file for?
